version: '3.6'

services:

  app:
    build:
      context: .
      dockerfile: DevDockerfile
    command: sh -c "wait-for db:5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

  celery_worker:
    build:
      context: .
      dockerfile: DevDockerfile
