version: '3.6'

services:

  app:
    env_file:
      - ./.env
    volumes:
      - static:/usr/src/app/staticfiles

  nginx:
    container_name: nginx
    command: sh -c '. wait-for app:8000 -- nginx -g "daemon off;"'
    depends_on:
      - app
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/wait-for.sh:/bin/wait-for
      - static:/var/www/app/staticfiles

volumes:
  static:
